config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
	root to: "visitors/home#index"
	get '/category/:id' => 'visitors/categories#show', as: :visitor_category
	get 'visitor_search_players', to: 'visitors/categories#visitor_search_players'
	get 'visitor_search_matches', to: 'visitors/categories#visitor_search_matches'
	get 'visitor_get_random_background', to: 'visitors/categories#visitor_get_random_background'
	get '/category_player/:id' => 'visitors/players#show', as: :visitor_player
	get '/category_match/:id' => 'visitors/matches#show', as: :visitor_match
	get 'visitor_like_player', to: 'visitors/players#visitor_like_player'
	get 'visitor_like_match', to: 'visitors/matches#visitor_like_match'
	get 'visitor_vote_match', to: 'visitors/matches#visitor_vote_player'
	get 'visitor_match_suggestion', to: 'visitors/matches#visitor_match_suggestion'
	get 'visitor_player_suggestion', to: 'visitors/players#visitor_player_suggestion'
	get 'visitor_category_suggestion', to: 'visitors/categories#visitor_category_suggestion'
	get 'info', to: 'visitors/home#info'
  scope module: 'admins' do
		get 'search_players', to: 'players#search_players'
		get 'search_matches', to: 'matches#search_matches'
		resources :suggestions
		resources :matches
		resources :players
		resources :categories
		resources :backgrounds
		resources :posts
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/background.rb
class Background < ApplicationRecord
	has_one_attached :background_image
  validates_presence_of :name, :background_image

  scope :get_random_background, -> do
  	find(Background.pluck(:id).sample)
  end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :matches
	has_many :players
  has_many :suggestion, as: :suggestable
	has_one_attached :category_image
  validates_presence_of :title, :min_rank, :max_rank
  validates_length_of :description, within: 10..350
  scope :active_categories, -> do
		where(active: true)
  end
  scope :order_by_rank, -> do
		order(:min_rank)
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :category
  belongs_to :player_1, class_name: "Player", foreign_key: :player_1_id, optional: true
  belongs_to :player_2, class_name: "Player", foreign_key: :player_2_id, optional: true
  belongs_to :winner, class_name: "Player", foreign_key: :winner_id, optional: true
  has_many :suggestion, as: :suggestable
  validates_presence_of :round
  validate :valid_match_users, :valid_winner
  private
    def valid_match_users
      if not (player_2.nil? || player_1.nil?)
    	  errors.add(:player_2, "must be different!") if player_2.eql? player_1
    	  errors.add(:player_1, " and player 2 must be on the same category!") if not player_2.category.eql? player_1.category
      end
      if player_2.nil? && player_1.nil?
        errors.add(:match, "You must choose at least one player")
        return
      elsif (not player_2.nil?) && (not player_1.nil?)
    	errors.add(:category, " doesn't match the players!") if not((category.eql? player_1.category) && (category.eql? player_2.category))
      end
    end
    def valid_winner
    	errors.add(:winner, "should exist in the match!") if not ((player_1.eql? winner) || (player_2.eql? winner)  || (winner.nil?))
    end
end

app/models/match_comment.rb
class MatchComment < ApplicationRecord
  belongs_to :match
end

app/models/player.rb
class Player < ApplicationRecord
	belongs_to :category
	has_many :player_1_matches, class_name: "Match", foreign_key: 'player_1_id'
	has_many :player_2_matches, class_name: "Match", foreign_key: 'player_2_id'
	has_many :winner_matches, class_name: "Match", foreign_key: 'winner_id'
	has_many :suggestion, as: :suggestable
	has_one_attached :profile_image
  validates_presence_of :name, :rank
end

app/models/post.rb
class Post < ApplicationRecord
	has_one_attached :post_image
	validates_presence_of :title, :description
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
	delegated_type :suggestable, types: %w[ Category Player Match ], dependent: :destroy
  enum status: { pending: 0, reopened: 1, closed: 2} 
  validates_presence_of :title, :description
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!, :sideBarTools 

	layout 'admins'

	def sideBarTools
		@current_admin = current_admin
		@categories = Category.all
	end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	layout 'visitors'
	def get_caegory
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def aoe_civilizations
		['', 'Chinese', 'Persians', 'Aztecs', 'Mayans', 'Malians', 'Huns', 'Khmer', 'Britons', 'Incas', 'Franks', 'Slavs', 'Mongols', 'Celts', 'Lithuanians', 'Japanese', 'Spanish', 'Magyars', 'Berbers', 'Cumans', 'Byzantines', 'The Ethiopians', 'Bulgarians', 'Vikings', 'Saracens', 'Teutons', 'Indians', 'Burmese', 'Koreans', 'Portuguese', 'Tatars', 'Italians', 'Malay', 'Vietnamese', 'Turks', 'Goths'].freeze
	end
	def get_random_background
		backgrounds = ['background_1.png', 'background_2.png', 'background_3.png', 'background_4.png', 'background_5.png', 'background_6.png']
		backgrounds[rand(backgrounds.length)]
	end
end

app/helpers/backgrounds_helper.rb
module BackgroundsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
		def matches_won(player)
			Match.where(winner: player).count
		end
		def total_matches(player)
			Match.where(player_1: player).count + Match.where(player_2: player).count  
		end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/match_comments_helper.rb
module MatchCommentsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/admins/_sideBar.html.erb
<nav id="sidebar">
    <div class="sidebar-header text-center">
        <h2><%= Admin %></h2>
        <p>NiluTorneo</p>
    </div>
    <div class="list-unstyled list-group">
        <a href="#homeSubmenu" class="btn btn-light list-group-item m-1" data-toggle="collapse"><i class="fas fa-bars"></i> Categories</a>
        <div class="collapse list-unstyled list-group" id="homeSubmenu">
            <a href="<%= categories_path %>" class="btn btn-light list-group-item m-2">Show All</a>
            <% @categories.order(:min_rank).each do |category|%> 
                <a href="<%= category_path(category) %>" class="btn btn-light list-group-item m-2"><%= category.title %></a>
            <% end %>
        </div>
        <a href="<%= players_path %>" class="btn btn-light list-group-item m-1"><i class="fas fa-users"></i> Players</a>
        <a href="<%= matches_path %>" class="btn btn-light list-group-item m-1"><i class="fas fa-shield-alt"></i> Matches</a>
        <a href="<%= backgrounds_path %>" class="btn btn-light list-group-item m-1"><i class="fas fa-images"></i> Backgrounds</a>
        <a href="<%= suggestions_path %>" class="btn btn-light list-group-item m-1"><i class="far fa-bell"></i> Suggestions <span class="badge bg-success p-2"><%= Suggestion.where(status: 0).or(Suggestion.where(status: 1)).count %></span></a>
        <a href="<%= posts_path %>" class="btn btn-light list-group-item m-1"><i class="fas fa-info"></i> Posts <span class="badge bg-success p-2"></a>

    </div>
    <div class="settings text-center">
        <h4 class="text-break" style="color:black;"><%=@current_admin.email%></h4>
        <%= link_to "Sign Out", destroy_admin_session_path, method: :delete, class: "btn btn-danger"%>
        <a href=" <%= root_path %>" class="btn btn-info"><i class="fas fa-home"></i></a>
    </div>
</nav>
<nav id="mobile-sidebar">
    <h4 class="text-break text-center" style="color:black;"><%=@current_admin.email%></h4>
    <div class="d-flex justify-content-between m-3">
        <%= link_to "Sign Out", destroy_admin_session_path, method: :delete, class: "btn btn-danger"%>
        <a href=" <%= root_path %>" class="btn btn-info"><i class="fas fa-home"></i></a>
    </div>
    <a href="#homeSubmenu2" class="btn btn-light list-group-item m-1" data-toggle="collapse"><i class="fas fa-bars"></i> Categories</a>
    <div class="collapse list-unstyled list-group" id="homeSubmenu2">
        <a href="<%= categories_path %>" class="btn btn-light list-group-item m-2">Show All</a>
        <% @categories.order(:min_rank).each do |category|%> 
            <a href="<%= category_path(category) %>" class="btn btn-light list-group-item m-2"><%= category.title %></a>
        <% end %>
    </div>
    <a href="<%= players_path %>" class="btn btn-light list-group-item m-1"><i class="fas fa-users"></i> Players</a>
    <a href="<%= matches_path %>" class="btn btn-light list-group-item m-1"><i class="fas fa-shield-alt"></i> Matches</a>
    <a href="<%= backgrounds_path %>" class="btn btn-light list-group-item m-1"><i class="fas fa-images"></i> Backgrounds</a>
    <a href="<%= suggestions_path %>" class="btn btn-light list-group-item m-1"><i class="far fa-bell"></i> Suggestions <span class="badge bg-success p-2"><%= Suggestion.where(status: 0).or(Suggestion.where(status: 1)).count %></span></a>
    <a href="<%= posts_path %>" class="btn btn-light list-group-item m-1"><i class="fas fa-info"></i> Posts <span class="badge bg-success p-2"></a>
    
</nav>