config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
	root to: "visitors/home#index"
	get '/category/:id' => 'visitors/categories#show', as: :visitor_category
	get 'visitor_search_players', to: 'visitors/categories#visitor_search_players'
	get 'visitor_search_matches', to: 'visitors/categories#visitor_search_matches'
	get 'visitor_get_random_background', to: 'visitors/categories#visitor_get_random_background'
	get '/category_player/:id' => 'visitors/players#show', as: :visitor_player
	get '/category_match/:id' => 'visitors/matches#show', as: :visitor_match
	get 'visitor_like_player', to: 'visitors/players#visitor_like_player'
	get 'visitor_like_match', to: 'visitors/matches#visitor_like_match'
	get 'visitor_vote_match', to: 'visitors/matches#visitor_vote_player'
	get 'visitor_match_suggestion', to: 'visitors/matches#visitor_match_suggestion'
	get 'visitor_player_suggestion', to: 'visitors/players#visitor_player_suggestion'
	get 'visitor_category_suggestion', to: 'visitors/categories#visitor_category_suggestion'
	get 'info', to: 'visitors/home#info'
  scope module: 'admins' do
		get 'search_players', to: 'players#search_players'
		get 'search_matches', to: 'matches#search_matches'
		resources :suggestions
		resources :matches
		resources :players
		resources :categories
		resources :backgrounds
		resources :posts
  end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :matches
	has_many :players
  has_many :suggestion, as: :suggestable
	has_one_attached :category_image
  validates_presence_of :title, :min_rank, :max_rank
  validates_length_of :description, within: 10..350
  scope :active_categories, -> do
		where(active: true)
  end
  scope :order_by_rank, -> do
		order(:min_rank)
  end
end

app/controllers/admins/categories_controller.rb
module Admins
  class CategoriesController < AdminsController
    before_action :get_rounds
    before_action :set_category, only:  [:show, :edit, :update, :destroy]

    # GET /categories
    def index
      @categories = Category.order(:min_rank)
    end

    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to @category
      else
        broadcast_errors @category, category_params 
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category
      else
        broadcast_errors @category, category_params 
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end
    
    private
      def get_rounds
        @category_rounds = Match.where(category_id: params[:id]).select(:round).distinct.map {|match| match.round }
      end
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def category_params
        params.require(:category).permit(:title, :description, :active, :min_rank, :max_rank, :register_link, :brackets_link, :start_date, :end_date, :category_image)
      end
  end
end

app/controllers/visitors/categories_controller.rb
module Visitors
	class CategoriesController < VisitorsController
    before_action :visitor_get_random_background
		def show
			@category = Category.find(params[:id])
			@players = Player.where(category_id: params[:id]).order(:name)
			@matches = Match.where(category_id: params[:id])
		end
		def visitor_search_players
      @players = Player.where(category_id: params[:category_id]).where("lower(name) LIKE ?", "%#{params[:search].downcase}%").order(:rank)
		end
		def visitor_search_matches
			rounds = params[:match][:rounds_filter].reject { |r| r.empty? }
      @matches = Match.where(category_id: params[:category_id])
      if not rounds.empty?
        @matches = @matches.where(round: rounds)
      end
		end

		def visitor_get_random_background
			@background = Background.get_random_background
		end
		
		def visitor_category_suggestion
			@category = Category.find(params[:id])
	  	@suggestion = @category.suggestion.build(title: params[:title], description: params[:description])
	  	if @suggestion.save
				notice = "Suggestion sent"
	  	else
				notice = "Something went wrong & we couldn't send your suggestion"
	  	end
	  		redirect_to visitor_category_path(@category), notice: notice
		end
	end 
end

app/helpers/categories_helper.rb
module CategoriesHelper
		def matches_won(player)
			Match.where(winner: player).count
		end
		def total_matches(player)
			Match.where(player_1: player).count + Match.where(player_2: player).count  
		end
end

app/views/admins/categories/_form.html.erb
<%= form_with(model: category, local: false) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
    <%= form.error_for :title, class: "text-danger" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
    <%= form.error_for :description, class: "text-danger" %>
  </div>

  <div class="field">
    <%= form.label :min_rank %>
    <%= form.number_field :min_rank, class: "form-control" %>
    <%= form.error_for :min_rank, class: "text-danger" %>
  </div>

  <div class="field">
    <%= form.label :max_rank %>
    <%= form.number_field :max_rank, class: "form-control" %>
    <%= form.error_for :max_rank, class: "text-danger" %>
  </div>

  <div class="field">
    <%= form.label :register_link %>
    <%= form.text_area :register_link, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :brackets_link %>
    <%= form.text_area :brackets_link, class: "form-control" %>
  </div>

  <div class="field text-center">
    <%= form.label :active %>
    <%= form.check_box :active, {checked: true, class: "form-control"} %>
  </div>
  
  <% if category.category_image.present? %>
    <div id="category_image">
      <%= image_tag category.category_image, class: "rounded mx-auto d-block mt-2" %>
    </div>
    <%= form.file_field :category_image, class: "mt-2 mx-auto d-block" %>
  <% else %>
    <%= form.file_field :category_image, class: "mt-2 form-control" %> 
  <% end %>
  
  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, class: "form-control" %>
  </div>


  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-block mb-2 mt-2" %>
  </div>
<% end %>

app/views/admins/categories/edit.html.erb
<div class="container">
	<h1>Editing Category</h1>
	<%= render 'form', category: @category %>
	<%= link_to 'Show', @category, class: "btn btn-secondary btn-block"%>
	<%= link_to 'Back', categories_path, class: "btn btn-secondary btn-block" %>
</div>

app/views/admins/categories/index.html.erb
<div class="container">
  <h2 class="d-flex justify-content-between mb-4">
    <span>Categories <span class="badge badge-secondary"><%= Category.all.count %></span></span>
      <%= link_to 'New Category', new_category_path, class: 'btn btn-primary'%>
  </h2>
  <% @categories.each do |category| %>
    <%= link_to category_path(category), class: "text-decoration-none" do %>
      <div class="card mb-2 category-card">
        <h5 class="card-header text-primary d-flex justify-content-between">
          <%= category.title %> (<%= category.min_rank %>-<%= category.max_rank %>)
          <% if category.active %>
            <span class="badge bg-success text-light ">Active</span>
          <% else %>
            <span class="badge bg-danger text-light">Inactive</span>
          <% end %>

        </h5>
        <div class="row">
          <div class="card-body">
            <% if category.category_image.present? %>
                <div class="header-image rounded" style="background-image: url(<%= url_for(category.category_image) %>);"></div>
              <% end %>
          </div>
          <div class="card-body text-secondary">
            <span class="card-title text-secondary h5">
              <span>
              <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger float-right ml-1" %>
              <%= link_to 'Edit', edit_category_path(category), class: "btn btn-primary float-right mr-1" %>
              </span>
              <%= category.description %>
              <h6 class="text-secondary mb-0">
                Start: <%= category.start_date %>
              </h6>
              <% if category.register_link.present? %>
                <h6 class="text-primary"><a href="<%= category.register_link %>" target="_blank">Registration Link</a></h6>
              <% end %>
            </span>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/admins/categories/new.html.erb
<div class="container">
	<h1>New Category</h1>
	<%= render 'form', category: @category %>
	<%= link_to 'Back', categories_path, class: "btn btn-secondary btn-block"%>
</div>

app/views/admins/categories/show.html.erb
<div class="row">
  <div class="col-md-3 mb-3">
    <div class="card">
      <div class="card-body">
        <h2 class="card-title text-primary "><%= @category.title %> (<%= @category.min_rank %>-<%= @category.max_rank %>)</h2>
        <h3 class="text-secondary"><%= @category.description %></h3>
        <% if @category.register_link.present? %>
          <h5 class="text-primary"><a href="<%= @category.register_link %>" target="_blank">Registration Link</a></h5>
        <% end %>
        <h6 class="text-secondary"><%= @category.start_date.strftime("%B %d %Y") %> - <%= @category.end_date.strftime("%B %d %Y") %></h6>
        <% if @category.category_image.present? %>
          <div class="text-center" id="category_image">
            <%= image_tag @category.category_image, class: "rounded mb-2" %>
          </div>
        <% end %>
        <%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-secondary btn-block mb-1'%> 
        <%= link_to 'Back', categories_path, class: 'btn btn-secondary btn-block mb-1' %>
        <%= link_to 'Destroy', @category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-block" %>
      </div>
    </div>
  </div>
  <div class="col-md-4 mb-4">
    <div class="card">
      <div class="card-body text-center">
        <h3 class="card-title">Players(<%= @category.title %>) <span class="badge badge-secondary"><%= Player.where(category: @category).count %></span></h3>
        <% @category.players.order(:rank).each do |player|%>
          <%= link_to edit_player_path(player), class: "text-decoration-none" do%>
            <div class="card mb-1">
              <div class="card-body p-1 text-center">
                <h5 class="card-title"><%= player.name %> (<%= player.rank %>)</h5>
                <span class="text-secondary">
                  Total Matches: <%= total_matches(player) %>
                  | 
                  Wins: <%= matches_won(player) %>
                </span>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4 mb-4">
    <div class="card">
      <div class="card-body text-center">
        <h3 class="card-title">Matches(<%= @category.title %>) <span class="badge badge-secondary"><%= Match.where(category: @category).count %></span></h3>
        <% @category_rounds.sort.each do |round| %>
          <h5>Round <%= round %></h5>
          <% @category.matches.where(round: round).each do |game_match|%>
            <%= link_to edit_match_path(game_match), class: "text-decoration-none" do%>
              <div class="card mb-1">
                <div class="card-body p-1 text-center">
                  <h5 class="card-title text-secondary">
                    <% if game_match.player_1.eql? game_match.winner %>
                      <span class="text-success"><%= game_match.player_1.present? ? game_match.player_1.name : "" %>(<%= game_match.player_1.present? ? game_match.player_1.rank : "" %>)</span>
                      vs
                      <span class="text-secondary"><%= game_match.player_2.present? ? game_match.player_2.name : "" %>(<%= game_match.player_2.present? ? game_match.player_2.rank : "" %>)</span>
                    <% elsif game_match.player_2.eql? game_match.winner %>
                      <span class="text-secondary"><%= game_match.player_1.present? ? game_match.player_1.name : "" %>(<%= game_match.player_1.present? ? game_match.player_1.rank : "" %>)</span>
                      vs
                      <span class="text-success"><%= game_match.player_2.present? ? game_match.player_2.name : "" %>(<%= game_match.player_2.present? ? game_match.player_2.rank : "" %>)</span>
                    <% else %>
                      <span><%= game_match.player_1.present? ? game_match.player_1.name : "" %>(<%= game_match.player_1.present? ? game_match.player_1.rank : "" %>)</span>
                      vs
                      <span><%= game_match.player_2.present? ? game_match.player_2.name : "" %>(<%= game_match.player_2.present? ? game_match.player_2.rank : "" %>)</span>
                    <% end %>
                  </h5>
                  <h6 class="card-text text-secondary">
                  </h6>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>