config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
	root to: "visitors/home#index"
	get '/category/:id' => 'visitors/categories#show', as: :visitor_category
	get 'visitor_search_players', to: 'visitors/categories#visitor_search_players'
	get 'visitor_search_matches', to: 'visitors/categories#visitor_search_matches'
	get 'visitor_get_random_background', to: 'visitors/categories#visitor_get_random_background'
	get '/category_player/:id' => 'visitors/players#show', as: :visitor_player
	get '/category_match/:id' => 'visitors/matches#show', as: :visitor_match
	get 'visitor_like_player', to: 'visitors/players#visitor_like_player'
	get 'visitor_like_match', to: 'visitors/matches#visitor_like_match'
	get 'visitor_vote_match', to: 'visitors/matches#visitor_vote_player'
	get 'visitor_match_suggestion', to: 'visitors/matches#visitor_match_suggestion'
	get 'visitor_player_suggestion', to: 'visitors/players#visitor_player_suggestion'
	get 'visitor_category_suggestion', to: 'visitors/categories#visitor_category_suggestion'
	get 'info', to: 'visitors/home#info'
  scope module: 'admins' do
		get 'search_players', to: 'players#search_players'
		get 'search_matches', to: 'matches#search_matches'
		resources :suggestions
		resources :matches
		resources :players
		resources :categories
		resources :backgrounds
		resources :posts
  end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :matches
	has_many :players
  has_many :suggestion, as: :suggestable
	has_one_attached :category_image
  validates_presence_of :title, :min_rank, :max_rank
  validates_length_of :description, within: 10..350
  scope :active_categories, -> do
		where(active: true)
  end
  scope :order_by_rank, -> do
		order(:min_rank)
  end
end

app/controllers/admins/categories_controller.rb
module Admins
  class CategoriesController < AdminsController
    before_action :get_rounds
    before_action :set_category, only:  [:show, :edit, :update, :destroy]

    # GET /categories
    def index
      @categories = Category.order(:min_rank)
    end

    def show
    end

    # GET /categories/new
    def new
      @category = Category.new
    end

    # GET /categories/1/edit
    def edit
    end

    # POST /categories
    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to @category
      else
        broadcast_errors @category, category_params 
      end
    end

    # PATCH/PUT /categories/1
    def update
      if @category.update(category_params)
        redirect_to @category
      else
        broadcast_errors @category, category_params 
      end
    end

    # DELETE /categories/1
    def destroy
      @category.destroy
      redirect_to categories_url, notice: 'Category was successfully destroyed.'
    end
    
    private
      def get_rounds
        @category_rounds = Match.where(category_id: params[:id]).select(:round).distinct.map {|match| match.round }
      end
      # Use callbacks to share common setup or constraints between actions.
      def set_category
        @category = Category.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def category_params
        params.require(:category).permit(:title, :description, :active, :min_rank, :max_rank, :register_link, :brackets_link, :start_date, :end_date, :category_image)
      end
  end
end

app/controllers/visitors/categories_controller.rb
module Visitors
	class CategoriesController < VisitorsController
    before_action :visitor_get_random_background
		def show
			@category = Category.find(params[:id])
			@players = Player.where(category_id: params[:id]).order(:name)
			@matches = Match.where(category_id: params[:id])
		end
		def visitor_search_players
      @players = Player.where(category_id: params[:category_id]).where("lower(name) LIKE ?", "%#{params[:search].downcase}%").order(:rank)
		end
		def visitor_search_matches
			rounds = params[:match][:rounds_filter].reject { |r| r.empty? }
      @matches = Match.where(category_id: params[:category_id])
      if not rounds.empty?
        @matches = @matches.where(round: rounds)
      end
		end

		def visitor_get_random_background
			@background = Background.get_random_background
		end
		
		def visitor_category_suggestion
			@category = Category.find(params[:id])
	  	@suggestion = @category.suggestion.build(title: params[:title], description: params[:description])
	  	if @suggestion.save
				notice = "Suggestion sent"
	  	else
				notice = "Something went wrong & we couldn't send your suggestion"
	  	end
	  		redirect_to visitor_category_path(@category), notice: notice
		end
	end 
end

app/controllers/visitors/home_controller.rb
module Visitors
	class HomeController < VisitorsController
	  def index
	  	@categories = Category.active_categories.order_by_rank
	  	@posts = Post.where(active: true).order(:created_at).limit(1)
	  end
	  def info
	  	@posts = Post.where(active: true)
	  end
	end
end

app/controllers/visitors/match_comments_controller.rb
module Visitors
  class MatchCommentsController < VisitorsController
    before_action :set_match_comment

    # GET /match_comments
    def index
      @match_comments = MatchComment.all
    end

    # GET /match_comments/1
    def show
    end

    # GET /match_comments/new
    def new
      @match_comment = MatchComment.new
    end

    # GET /match_comments/1/edit
    def edit
    end

    # POST /match_comments
    def create
      @match_comment = MatchComment.new(match_comment_params)

      if @match_comment.save
        redirect_to @match_comment, notice: 'Match comment was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /match_comments/1
    def update
      if @match_comment.update(match_comment_params)
        redirect_to @match_comment, notice: 'Match comment was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /match_comments/1
    def destroy
      @match_comment.destroy
      redirect_to match_comments_url, notice: 'Match comment was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_match_comment
        @match_comment = MatchComment.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def match_comment_params
        params.require(:match_comment).permit(:descrption, :match_id)
      end
  end

app/controllers/visitors/matches_controller.rb
module Visitors
	class MatchesController < VisitorsController
	  def show
	  	@match = Match.find(params[:id])
	  end
	  def visitor_like_match
	  	@match = Match.find(params[:id])
      @match.likes = @match.likes.to_i + 1
      if @match.save
        notice = " +1 like and now has #{@match.likes}"
      end
      redirect_to visitor_match_path(@match)
	  end
	  def visitor_vote_player
	  	@match = Match.find(params[:id])
	  	if not params[:vote_player].empty?
		  	votePlayer = Player.find(params[:vote_player])
		  	if votePlayer.eql? @match.player_1
		  		@match.vote_player_1 =  @match.vote_player_1.to_i + 1
		  	elsif votePlayer.eql? @match.player_2
		  		@match.vote_player_2 =  @match.vote_player_2.to_i + 1
		  	end
		  	@match.save
		  end
      redirect_to visitor_match_path(@match)
	  end
	  def visitor_match_suggestion
	  	@match = Match.find(params[:id])
	  	@suggestion = @match.suggestion.build(title: params[:title], description: params[:description])
	  	if @suggestion.save
				notice = "Suggestion sent"
	  	else
				notice = "Something went wrong & we couldn't send your suggestion"
	  	end
	  		redirect_to visitor_match_path(@match), notice: notice
	  end
	  # private 
	  # 	def match_params
	  # 		params.require(:match).permit(:id, :title, :description)
	  # 	end
	end
end

app/controllers/visitors/players_controller.rb
module Visitors
	class PlayersController < VisitorsController
	  def show
	  	@player = Player.find(params[:id])
	  	@total_matches = Match.where(player_1: @player).or(Match.where(player_1: @player))
  		@matches_won = Match.where(player_1: @player).where(winner: @player).or(Match.where(player_2: @player).where(winner: @player))	
	  end
	  def visitor_like_player
      @player = Player.find(params[:id])
      @player.likes = @player.likes.to_i + 1
      if @player.save
        notice = "#{@player.name} got +1 like and now has #{@player.likes}"
      end
        redirect_to visitor_player_path(@player)
		end
		def visitor_player_suggestion
			@player = Player.find(params[:id])
	  	@suggestion = @player.suggestion.build(title: params[:title], description: params[:description])
	  	if @suggestion.save
				notice = "Suggestion sent"
	  	else
				notice = "Something went wrong & we couldn't send your suggestion"
	  	end
	  		redirect_to visitor_player_path(@player), notice: notice
		end
	end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	layout 'visitors'
	def get_caegory
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
		def matches_won(player)
			Match.where(winner: player).count
		end
		def total_matches(player)
			Match.where(player_1: player).count + Match.where(player_2: player).count  
		end
end

app/views/visitors/categories/_matches.html.erb
<% @matches.select(:round).distinct.map {|match| match.round }.sort.each do |round| %>
  <div class="card mb-2">
    <h5 class="card-header">Round <%= round %></h5>
    <div class="card-body m-0 p-0">
      <% @matches.where(round: round).each do |game_match| %>
        <%= link_to visitor_match_path(game_match), class: "text-decoration-none" do %>
          <div class="card match-players-card">
            <div class="card-body">
              <p class="text-dark match-date"> 
                <%= game_match.date.strftime("%m/%d/%Y")%> 
              </p> 
              <span class="card-title text-secondary h4">
                <% if (game_match.player_1.present? && game_match.player_2.present?) && (game_match.player_1.eql?(game_match.winner) || game_match.player_2.eql?(game_match.winner)) %>
                  <% if game_match.player_1.eql?(game_match.winner) %>
                    <span class="text-success"><%= game_match.player_1.name %></span> <!-- (<= game_match.player_1.rank >) -->
                    <span>vs</span>
                    <span class="text-danger"><%= game_match.player_2.name %></span> <!-- (<= game_match.player_2.rank >) -->
                  <% else %>
                    <span class="text-danger"><%= game_match.player_1.name %></span> <!-- (<= game_match.player_1.rank >) -->
                    <span>vs</span>
                    <span class="text-success"><%= game_match.player_2.name %></span> <!-- (<= game_match.player_2.rank >) -->
                  <% end %> 
                <% else %>
                  <% if game_match.player_1.present? %>
                    <%= game_match.player_1.name %> <!-- (<= game_match.player_1.rank >) -->
                  <% end %>
                  <% if game_match.player_2.present? %>
                    <span class="text-info">vs</span>
                    <%= game_match.player_2.name %> <!-- (<= game_match.player_2.rank >) -->
                  <% end %>
                <% end %>
              </span>
            </div>
          </div>
        <% end %>
        <hr>
      <% end %>
    </div>
  </div>
<% end %>

app/views/visitors/categories/_players.html.erb
<% @players.each do |player| %>
  <%= link_to visitor_player_path(player), class: "text-decoration-none" do %>
    <li class="list-group-item player-field">
      <div class="row">
        <div class="col-md-2">
          <% if player.profile_image.present? %>
            <div class="header-image position-absolute" style="background-image: url(<%= url_for(player.profile_image) %>);"></div>
          <% end %>
        </div>
        <div class="col-md-8 col-sm-8 mt-3 mb-3">
          <h5 class="mb-1 text-dark d-inline"><%= player.name %> <!-- (<= player.rank != 0 ? player.rank : "-" >) --></h5><span class="text-info"><%= player.seeding %></span>
        </div>
      </div>
    </li>
  <% end %>
<% end %>

app/views/visitors/categories/show.html.erb
<div class="jumbotron p-3 mb-0" id="main-wrapper">
	<%= link_to "Atras", root_path %>
	<a href="<%= @category.register_link %>" class="register-button" target="_blank" role="button">Registrarse</a>
	<% if @category.category_image.present? %>
		<div id="category_image">
			<%= image_tag @category.category_image, class: "rounded mx-auto d-block", style: "width:auto;height:175px" %>
		</div>
	<% end %>
  <p class="display-4 text-center m-0"> <%= @category.title %> <span style="font-size: 50%;">(<%= @category.min_rank %>-<%= @category.max_rank %>)</span> </p>
  <p class="text-center lead m-0"> <%= @category.description %> </p>
  <p class="text-center mb-2"> <%= @category.start_date.strftime("%d/%m") %> - <%= @category.end_date.strftime("%d/%m") %> </p>
  	<div class="text-center">
		<button onclick="newSuggestion()" class="btn btn-info col-md-3 col-sm-6">Sugerencias!</button>
		<br>
		<% if @category.brackets_link.present? %>
			<button onclick="show_brackets()" class="btn btn-secondary col-md-3 col-sm-6 mt-1">Brackets!</button>
		<% end %>
	</div>
</div>
<% if @background.present? %>
	<div class="big-container" id="background_image_container" style="background-image: url(<%= url_for(@background.background_image) %>)">
	<%= form_tag(visitor_get_random_background_path, method: "get", remote: true) do %>
		<span id="change_background_button">
			<a class="btn btn-success m-2" onclick="changeBackgroundImage()"><i class="fas fa-images"></i></a>
			<%= submit_tag "Search", class: "d-none", id: "backgroud_submit" %>
		</span>
	<% end %>
<% else %>
	<div class="big-container bg-info" id="background_image_container">
<% end %>
	<div class="row p-3 m-0">
		<div class="col-md-4 mb-3 box-container">
			<div class="card text-center render-container">
			  <h4 class="card-header card-main-header">
			    Jugadores <span class="badge badge-secondary" id="players-badge"> <%= @players.all.count %> </span><span class="badge badge-info float-right text-dark">Seeding</span>
			  </h4>
			  <div class="card-body">
					<%= form_tag(visitor_search_players_path, method: "get", remote: true) do %>
						<div class="input-group">
							<span class="input-group-text" id="basic-addon1"><i class="fas fa-filter"></i></span>
						  	<%= text_field_tag :search, '', class: 'form-control', placeholder: 'Search Player...', onkeydown:'clickSubmitPlayers();' %>
						</div>
						<%= hidden_field_tag :category_id, @category.id %>
						<%= submit_tag "Search", class: "d-none", id: "search_submit" %>
					<% end %>
					<ul class="list-group list-group-flush mt-3" id="players-container">
    					<%= render 'players' %>
  					</ul>
			  </div>
			  <div class="card-footer text-muted">
			  	<%= @category.title %>
			  </div>
			</div>
		</div>
		<div class="col-md-8 mb-3 box-container">
			<div class="card text-center render-container">
			  <h4 class="card-header card-main-header">
			    Partidas: <span class="badge badge-secondary" id="matches-badge"> <%= @matches.all.count %> </span>
			  </h4>
			  <div class="card-body">
					<%= form_tag(visitor_search_matches_path, method: "get", remote: true) do %>
				          <div class="input-group">
			                <span class="input-group-text" id="basic-addon1"><i class="fas fa-filter"></i>Rounds</span>
			                <%= collection_check_boxes(:match, :rounds_filter, Match.where(category: @category).order(:round).select(:round).distinct, :round, :round, {}, {class: "custom-control custom-checkbox", onchange:'clickSubmitMatches();'}) do |round| %>
			                  <span class="d-none">
			                    <%= round.check_box %>
			                  </span>
			                  <%= round.label(class: "round-checkbox-label mr-2 ml-2", onclick: "activateCheckbox(this)") %>
			                <% end %>
							<%= hidden_field_tag :category_id, @category.id %>
				            <%= submit_tag "Search", class: "d-none", id: "search_submit_matches" %>
				          </div>
				    <% end %>

					<ul class="list-group list-group-flush mt-3" id="matches-container">
    					<%= render 'matches' %>
  					</ul>
			  </div>
			  <div class="card-footer text-muted">
			  	<%= @category.title %>
			  </div>
			</div>
		</div>
	</div>
	<div id="footer">
		<div class="footer-up">
			<a class="btn twitch-button" href="https://www.twitch.tv/nilusa" target="_blank" role="button"><i class="fab fa-twitch"></i></a>
			<a class="btn discord-button" href="https://discord.gg/kAGB9G9seF" target="_blank" role="button"><i class="fab fa-discord"></i></a>
			<a class="btn btn-info" href="https://docs.google.com/document/d/1qmk3QK-E5KjPnmKYDkGHqGd-oOpbTo0TPQQ2eHtUmok/edit?usp=sharing" target="_blank" role="button">Reglas <i class="fas fa-book"></i></a>
			<p class="disclaimer-button btn btn-primary"><i class="fas fa-info-circle"></i>
		  		<span class="disclaimer-info">All images belong to their respective owners.<br>Todas las imágenes le pertenecen al dueño respectivo.</span>
		  	</p>
		</div>
		<div class="footer-down">
			<a class="btn btn-dark" href="https://github.com/pulgamecanica" target="_blank" role="button">By pulgamecanica <i class="fab fa-github"></i></a>
			<% if current_admin.present? %>
				<%= link_to categories_path do %>
					<div class="mt-1">
						<button class= "btn btn-seconday d-block m-auto bg-secondary"><span> ADMINS </span><i class="fas fa-tools"></i></button>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
</div>
<% if @category.brackets_link.present? %>
	<div id="brackets">
		<iframe src="<%= @category.brackets_link %>" allowfullscreen frameborder="0"></iframe>
		<i class="fas fa-times-circle" onclick="closeImage()"></i>
	</div>
<% end %>
<span id="imageWindowDisplayer" class="text-center p-5">
	<%= form_with(url: visitor_category_suggestion_path, method: "get", remote: false) do |form| %>
		<h2>Sugerencia</h2>
		<h6><%= @category.title %></h6>
		<%= form.hidden_field(:id, value: @category.id) %>
		<div class="field">
		    <label>Título</label>
		    <%= form.text_field :title, placeholder: "Título", class: "form-control"%>
	  	</div>
	  	<div class="field">
			<label>Descripción</label>
		    <%= form.text_area :description, placeholder: "Descripción", class: "form-control" %>
	  	</div>
		<%= form.submit "Enviar Sugerencia", class: " mt-2 btn btn-success btn-block"%>
	<% end %>
	<i class="fas fa-times-circle" onclick="closeImage()"></i>
</span>
<script>
var prevScrollpos = window.pageYOffset;
window.onscroll = function() {
var currentScrollPos = window.pageYOffset;
  if (prevScrollpos > currentScrollPos) {
    document.getElementById("footer").style.bottom = "0.5em";
  } else {
    document.getElementById("footer").style.bottom = "-150px";
  }
  prevScrollpos = currentScrollPos;
}
function clickSubmitPlayers() {
  $(search_submit).trigger("click");
}
function clickSubmitMatches() {
  $(search_submit_matches).trigger("click");
}
function activateCheckbox(label) {
  if ($(label).hasClass("active-round-checkbox-label")) {
    $(label).removeClass("active-round-checkbox-label");
  }else{
    $(label).addClass("active-round-checkbox-label");
  }
}
function changeBackgroundImage(){
	$(backgroud_submit).trigger("click");
}
function newSuggestion() {
	document.getElementById("main-wrapper").style.opacity = 0.3;
	document.getElementById("background_image_container").style.opacity = 0.3;
	document.getElementById('imageWindowDisplayer').style.display = "block";
}
function closeImage() {
	document.getElementById("main-wrapper").style.opacity = 1;
	document.getElementById("background_image_container").style.opacity = 1;
	document.getElementById('imageWindowDisplayer').style.display = "none";
	document.getElementById('brackets').style.display = "none";
}
function show_brackets() {
	document.getElementById("main-wrapper").style.opacity = 0.3;
	document.getElementById("background_image_container").style.opacity = 0.3;
	document.getElementById('brackets').style.display = "block";
}
$(document).keydown(function(e) {
	if (e.keyCode == 27) 
   		closeImage();
});
</script>

app/views/visitors/categories/visitor_get_random_background.js.erb
$("#background_image_container").css("background-image", "url(<%= url_for(@background.background_image) %>)");

app/views/visitors/categories/visitor_search_matches.js.erb
$("#matches-container").html("<%= j render 'matches' %>");
$("#matches-badge").html("<%= @matches.all.count %>")

app/views/visitors/categories/visitor_search_players.js.erb
$("#players-container").html("<%= j render 'players' %>");
$("#players-badge").html("<%= @players.all.count %>")