config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
	root to: "visitors/home#index"
	get '/category/:id' => 'visitors/categories#show', as: :visitor_category
	get 'visitor_search_players', to: 'visitors/categories#visitor_search_players'
	get 'visitor_search_matches', to: 'visitors/categories#visitor_search_matches'
	get 'visitor_get_random_background', to: 'visitors/categories#visitor_get_random_background'
	get '/category_player/:id' => 'visitors/players#show', as: :visitor_player
	get '/category_match/:id' => 'visitors/matches#show', as: :visitor_match
	get 'visitor_like_player', to: 'visitors/players#visitor_like_player'
	get 'visitor_like_match', to: 'visitors/matches#visitor_like_match'
	get 'visitor_vote_match', to: 'visitors/matches#visitor_vote_player'
	get 'visitor_match_suggestion', to: 'visitors/matches#visitor_match_suggestion'
	get 'visitor_player_suggestion', to: 'visitors/players#visitor_player_suggestion'
	get 'visitor_category_suggestion', to: 'visitors/categories#visitor_category_suggestion'
	get 'info', to: 'visitors/home#info'
  scope module: 'admins' do
		get 'search_players', to: 'players#search_players'
		get 'search_matches', to: 'matches#search_matches'
		resources :suggestions
		resources :matches
		resources :players
		resources :categories
		resources :backgrounds
		resources :posts
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :category
  belongs_to :player_1, class_name: "Player", foreign_key: :player_1_id, optional: true
  belongs_to :player_2, class_name: "Player", foreign_key: :player_2_id, optional: true
  belongs_to :winner, class_name: "Player", foreign_key: :winner_id, optional: true
  has_many :suggestion, as: :suggestable
  validates_presence_of :round
  validate :valid_match_users, :valid_winner
  private
    def valid_match_users
      if not (player_2.nil? || player_1.nil?)
    	  errors.add(:player_2, "must be different!") if player_2.eql? player_1
    	  errors.add(:player_1, " and player 2 must be on the same category!") if not player_2.category.eql? player_1.category
      end
      if player_2.nil? && player_1.nil?
        errors.add(:match, "You must choose at least one player")
        return
      elsif (not player_2.nil?) && (not player_1.nil?)
    	errors.add(:category, " doesn't match the players!") if not((category.eql? player_1.category) && (category.eql? player_2.category))
      end
    end
    def valid_winner
    	errors.add(:winner, "should exist in the match!") if not ((player_1.eql? winner) || (player_2.eql? winner)  || (winner.nil?))
    end
end

app/controllers/admins/matches_controller.rb
module Admins
  class MatchesController < AdminsController
    before_action :set_match, only: [:edit, :update, :destroy]
    # GET /matches
    def index
      @matches = Match.order(:round, :category_id)

    end
    
    # GET /matches/new
    def new
      @match = Match.new
    end

    # GET /matches/1/edit
    def edit
    end

    # POST /matches
    def create
      @match = Match.new(match_params)
      if @match.save
        redirect_to edit_match_path(@match)
      else
        render :new
      end
        
    end

    # PATCH/PUT /matches/1
    def update
      if @match.update(match_params)
        notice = nil
      else
        notice = @match.errors.full_messages.join(" - ")
      end
        redirect_to edit_match_path(@match), notice: notice
    end

    # DELETE /matches/1
    def destroy
      @match.destroy
      redirect_to matches_url, notice: 'Match was successfully destroyed.'
    end

    def search_matches
      rounds = params[:match][:rounds_filter].reject { |r| r.empty? }
      result = Match.all
      if not params[:category_filter].empty?
        result = Match.where(category_id: params[:category_filter])
      end
      if not rounds.empty?
        result = result.where(round: rounds)
      end
      @matches = result
    end
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_match
        @match = Match.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def match_params
        params.require(:match).permit(:date, :category_id, :player_1_id, :player_2_id, :round, :winner_id, :player_1_civilization, :player_2_civilization, :vote_player_1, :vote_player_2)
      end
  end
end

app/controllers/visitors/matches_controller.rb
module Visitors
	class MatchesController < VisitorsController
	  def show
	  	@match = Match.find(params[:id])
	  end
	  def visitor_like_match
	  	@match = Match.find(params[:id])
      @match.likes = @match.likes.to_i + 1
      if @match.save
        notice = " +1 like and now has #{@match.likes}"
      end
      redirect_to visitor_match_path(@match)
	  end
	  def visitor_vote_player
	  	@match = Match.find(params[:id])
	  	if not params[:vote_player].empty?
		  	votePlayer = Player.find(params[:vote_player])
		  	if votePlayer.eql? @match.player_1
		  		@match.vote_player_1 =  @match.vote_player_1.to_i + 1
		  	elsif votePlayer.eql? @match.player_2
		  		@match.vote_player_2 =  @match.vote_player_2.to_i + 1
		  	end
		  	@match.save
		  end
      redirect_to visitor_match_path(@match)
	  end
	  def visitor_match_suggestion
	  	@match = Match.find(params[:id])
	  	@suggestion = @match.suggestion.build(title: params[:title], description: params[:description])
	  	if @suggestion.save
				notice = "Suggestion sent"
	  	else
				notice = "Something went wrong & we couldn't send your suggestion"
	  	end
	  		redirect_to visitor_match_path(@match), notice: notice
	  end
	  # private 
	  # 	def match_params
	  # 		params.require(:match).permit(:id, :title, :description)
	  # 	end
	end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/admins/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, {}, {class: "form-control"} %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.order(:min_rank), :id, :title, {}, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :player_1_id %>
    <%= form.collection_select :player_1_id, Player.order(:name), :id, :name, {include_blank: true}, class: "form-control" %>
  </div>

  <div class="field">
    <label>Player 1 Civ</label>
    <%= form.select :player_1_civilization, options_for_select(aoe_civilizations.sort(), match.player_1_civilization), {}, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :player_2_id %>
    <%= form.collection_select :player_2_id, Player.order(:name), :id, :name, {include_blank: true}, class: "form-control" %>
  </div>

  <div class="field">
    <label>Player 2 Civ</label>
    <%= form.select :player_2_civilization, options_for_select(aoe_civilizations.sort(), match.player_2_civilization), {}, class: "form-control" %>
  </div>
  <% if match.persisted? %>
    <div class="field">
      <%= form.label :winner_id %>(Optional)
      <% if match.player_1.nil? || match.player_2.nil? %>
        <%= form.select :winner_id, [], {}, disabled: true %>
      <% else %>
        <%= form.select :winner_id, options_for_select([[match.player_1.name, match.player_1.id], [match.player_2.name, match.player_2.id]], match.winner_id), {include_blank: true }, class: "form-control" %>
      <% end %>
    </div>
  <% else %>
    <div class="field">
      <%= form.label :winner_id %>(Optional)
      <%= form.collection_select :winner_id, Player.order(:rank), :id, :name, {include_blank: true }, class: "form-control" %>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :round %>
    <%= form.number_field :round, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-block mt-2" %>
  </div>
<% end %>

app/views/admins/matches/_matches.html.erb
<% @matches.order(:round).each do |game_match| %>
  <%= link_to edit_match_path(game_match), class: "text-decoration-none" do %>
    <div class="card mb-2">
      <h6 class="card-header">
        Round <%= game_match.round %> - <%=game_match.category.title %> 
        <p class="float-right text-dark"> 
          <%= game_match.date.strftime("%m/%d/%Y")%> 
        </p> 
      </h6>
      <div class="card-body">
        <span class="card-title text-secondary h5">
          <% if game_match.player_1.present? %>
            <%= game_match.player_1.name %> (<%= game_match.player_1.rank %>)
          <% end %>
          vs
          <% if game_match.player_2.present? %>
            <%= game_match.player_2.name %> (<%= game_match.player_2.rank %>)
          <% end %>
          <%= link_to 'Destroy', game_match, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger float-right ml-1" %>
          <%= link_to 'Edit', edit_match_path(game_match), class: "btn btn-primary float-right mr-1" %>
        </span>
        <p class="text-secondary mb-0">
          <% if game_match.likes.to_i != 0 %>
            <%= game_match.likes %> likes.
          <% end %>
        </p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admins/matches/edit.html.erb
<%= link_to 'Back', matches_path, class: 'btn btn-secondary mb-3' %>
<div class="row">
	<div class="col-md-3 mb-3">
		<div class="card">
			<div class="card-body">
				<h4 class="card-title">Editing Match</h4>
				<%= render 'form', match: @match %>
				<%= link_to 'Destroy', @match, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-block mt-1" %>
			</div>
		</div>
	</div>
	<div class="col-md-9">
		<div class="card">
			<div class="card-body text-center">
				<!-- IDEA: Maybe show ALL the category matches highlighting the match erdited.... -->
				<h2 class="card-title m-4">
			        Round <%= @match.round %> - <%=@match.category.title %> 
			    </h2>
			    <h3 class="text-secondary mb-2">
			    	<% if @match.player_1.present? %>
  						<%= link_to edit_player_path(@match.player_1), class: "text-decoration-none" do %>
				  			<%= @match.player_1.name %> (<%= @match.player_1.rank %>)
				  		<% end %>
				  	<% end %>
				  	vs
				  	<% if @match.player_2.present? %>
	  					<%= link_to edit_player_path(@match.player_2), class: "text-decoration-none" do %>
					  		<%= @match.player_2.name %> (<%= @match.player_2.rank %>)
					  	<% end %>
					<% end %>
				</h3>
				<% if @match.player_1_civilization.present? || @match.player_2_civilization.present?%>
					<h5 class="text-secondary mb-4">
				  		<%= @match.player_1_civilization.empty? ? "---" : @match.player_1_civilization %>
				  		vs 
				  		<%= @match.player_2_civilization.empty? ? "---" : @match.player_2_civilization %>
					</h5>
				<% end %>
				<h3 class="text-warning mb-4"> 
					<% if @match.winner.present? %>
			        	Winner: <%= @match.winner.name %> 
			        <% end %>
			    </h3> 
				<p> 
			        <%= @match.date %> 
			    </p> 

				<p class="text-secondary mb-0">
				  <% if @match.likes.to_i != 0 %>
		            <%= @match.likes %> likes.
		          <% end %>
				</p>
			</div>
		</div>
	</div>
</div>

app/views/admins/matches/index.html.erb
<div class="container">
  <h2 class="d-flex justify-content-between mb-4">
    <span>Matches <span class="badge badge-secondary" id="matches-badge"><%= Match.all.count %></span></span>
    <%= link_to 'New Match', new_match_path, class: 'btn btn-primary'%>
  </h2>
  <a href="#collapseExample" class="btn btn-secondary m-2 mb-3" data-toggle="collapse">
    <i class="fas fa-filter"></i> Filters
  </a>
  <div class="collapse mb-1 mt-1" id="collapseExample">
    <div class="p-2">
      <%= form_tag(search_matches_path, method: "get", remote: true) do %>
        <div class="row">
          <div class="input-group">
            <div class="col-md-6">
              <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1">Category</span>
                  <%= select_tag :category_filter, options_for_select(Category.order(:title).reverse_order.map { |cat| [cat.title, cat.id] }), include_blank: true, class: "custom-select", onchange:'clickSubmitMatches();'%>
              </div>
            </div>
            <div class="col-md-6">
              <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1">Rounds</span>
                <%= collection_check_boxes(:match, :rounds_filter, Match.order(:round).select(:round).distinct, :round, :round, {}, {class: "custom-control custom-checkbox", onchange:'clickSubmitMatches();'}) do |round| %>
                  <span class="d-none">
                    <%= round.check_box %>
                  </span>
                  <%= round.label(class: "round-checkbox-label", onclick: "activateCheckbox(this)") %>
                <% end %>
              </div>
            </div>
            <%= submit_tag "Search", class: "d-none", id: "search_submit" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div id="matches-container">
    <%= render 'matches' %>
  </div>
</div>
<script> 
function clickSubmitMatches() {
  $(search_submit).trigger("click");
}
function activateCheckbox(label) {
  if ($(label).hasClass("active-round-checkbox-label")) {
    $(label).removeClass("active-round-checkbox-label");
  }else{
    $(label).addClass("active-round-checkbox-label");
  }
}
</script>

app/views/admins/matches/new.html.erb
<div class="container">
	<h1 class="text-center">New Match</h1>
	<%= render 'form', match: @match %>
	<%= link_to 'Back', matches_path, class: "btn btn-secondary btn-block mt-2" %>
</div>

app/views/admins/matches/search_matches.js.erb
$("#matches-container").html("<%= j render 'matches' %>");